- src/components/Point/Point2d/Point2d.tsx
- src/components/Point/Point3d/Point3d.tsx
- src/components/PointCoordinates/PointCoordinates.tsx
- src/hooks/useDragNumber.ts
- src/hooks/useLevaUpdate.ts
- src/store.ts
- src/types/index.ts
- src/utils/input.ts
- src/utils/math.ts
This should make it easier for future updates where we might want to update the value from an external interface.
The component from the control pane was responsible for sanitizing the value before updating it to the store. This was working fine but we if we ever wanted to let the user update the store outside of the component, we would have had to trust the user that he reimplemented the logic for validating and sanitizing the updated value on its own.
When a value is updated, the store is now responsible for validating and sanitizing the updated value. If the value is incorrect it will throw. If the value if the same as the previous one, it will trow.
> When the minimum value of a number input is 30, and the user inputs "15". Then the newValue will be sanitized to 30 and the input field …
> Pushes sanitize function in the store update

- packages/leva/src/components/Monitor/Monitor.tsx
- packages/plugin-spring/src/SpringCanvas.tsx
Various improvements to the monitor and spring input. 
| Before | After |
|--------|------|
| <img width="287" alt="Screenshot 2021-02-15 at 19 03 52" src="https://user-images.githubusercontent.com/7217420/108082800-be867e80-7072-11eb-8de8-3992d7e15c44.png"> | <img width="288" alt="Screenshot 2021-02-15 at 19 03 15" src="https://user-images.githubusercontent.com/7217420/108082818-c514f600-7072-11eb-94af-875168f49814.png"> |
**Before**
https://user-images.githubusercontent.com/7217420/108081897-c134a400-7071-11eb-90ba-7d00bba888e2.mov 
**After**
https://user-images.githubusercontent.com/7217420/108081910-c42f9480-7071-11eb-886d-18c61a72ac47.mov
> Various style improvements of monitor and spring input

- example/src/App.tsx
- example/src/MultipleStores.tsx
- packages/leva/package.json
- packages/leva/src/components/Interval/interval-plugin.ts
- packages/leva/src/components/ValueInput/StyledInput.ts
- packages/leva/src/components/ValueInput/ValueInput.tsx
- packages/leva/src/components/Vector/vector-plugin.ts
- packages/leva/src/components/Vector/vector-utils.ts
- packages/leva/src/components/Vector2d/Joystick.tsx
- packages/leva/src/components/Vector2d/Vector2d.tsx
- packages/leva/src/components/Vector2d/index.ts
- packages/leva/src/components/Vector2d/vector2d-plugin.ts
- packages/leva/src/components/Vector3d/Vector3d.tsx
- packages/leva/src/components/Vector3d/index.ts
- packages/leva/src/components/Vector3d/vector3d-plugin.ts
- packages/leva/src/types/internal.ts
- packages/leva/src/types/public-types.ts
- packages/leva/src/utilities.ts
- packages/plugin-spring/src/spring-plugin.ts
- yarn.lock
This PR allows the following:
```js
const { size: { width, height }} = useControls({ size: { width: 100, height: 100 } })
```
So that the labels are nicely rendered with the initial of keys 👨‍🍳
> Vector all keys supported

- .codesandbox/ci.json
- package.json
- sandboxes/leva-advanced-panels/package.json
- sandboxes/leva-busy/package.json
- sandboxes/leva-minimal/package.json
- sandboxes/leva-plugin-spring/package.json
- sandboxes/leva-scroll/package.json
- sandboxes/leva-ui/package.json
- sandboxes/leva-ui/public/index.html
- sandboxes/leva-ui/src/App.js
- sandboxes/leva-ui/src/index.js
- sandboxes/leva-ui/src/styles.css
- yarn.lock
This PR makes code sandbox sandboxes in the `sandboxes/*` environment usable locally with refresh on code change.
In a terminal, from the lib root directory:
```bash
yarn watch
```
In another terminal, from the sandbox directory, run:
```bash
yarn start
```
To work, the sandboxes need to use the same React version as the lib. Some sandboxes were created using `"react": "17.0.0"`, while the lib dev deps use `"react": "^17.0.01"`. This resulted in `yarn` creating local `node_modules` in each sandbox, which eventually made the sandbox import two different versions of React (which breaks everything).
Also, sandboxes need to have preflight disabled. I'm not 100% sure what that means, but this boils down to changing the start script of each sandbox:
```js
// before
"start": "react-scripts …
```
> Chore: improves ci workflow

- demo/src/sandboxes/leva-busy/src/App.tsx
- packages/leva/src/components/UI/StyledUI.ts
- packages/leva/src/components/Vector/vector-plugin.ts
- packages/leva/src/components/Vector2d/Joystick.tsx
- packages/leva/src/components/Vector2d/Vector2d.tsx
- packages/leva/src/components/Vector2d/index.ts
- packages/leva/src/types/public-types.ts
Allows this:
```js
useControls({ noJoystickVector: { value: [1, 2], joystick: false } })
```
> Feat: no joystick on vector2d

- demo/src/sandboxes/leva-busy/src/App.tsx
- packages/leva/src/components/Control/Control.tsx
- packages/leva/src/components/Control/ControlInput.tsx
- packages/leva/src/components/Interval/Interval.tsx
- packages/leva/src/components/Interval/interval-plugin.ts
- packages/leva/src/components/Number/number-plugin.ts
- packages/leva/src/components/Vector/Vector.tsx
- packages/leva/src/components/Vector/vector-plugin.ts
- packages/leva/src/components/Vector2d/Vector2d.tsx
- packages/leva/src/components/Vector3d/Vector3d.tsx
- packages/leva/src/hooks/useInput.ts
- packages/leva/src/plugin.ts
- packages/leva/src/store.ts
- packages/leva/src/types/internal.ts
- packages/leva/src/types/public-types.ts
- packages/leva/src/utils/input.ts
- packages/leva/src/utils/math.ts
- packages/leva/stories/inputs/Vector.stories.tsx
- packages/plugin-spring/src/Spring.tsx
- packages/plugin-spring/src/spring-plugin.ts
First commit allows Vectors to be updated with only one of their keys.
API: 
```js
useControls({ vector: { value: [3, 4], lock: true }})
```
Edit: this commit also allows for math evaluation in number inputs!
> Feat: road to vector lock

- demo/src/sandboxes/leva-theme/src/App.jsx
- demo/src/sandboxes/leva-ui/src/App.jsx
- docs/configuration.md
- packages/leva/src/components/Folder/Folder.tsx
- packages/leva/src/components/Folder/StyledFolder.ts
- packages/leva/src/components/Leva/Leva.tsx
- packages/leva/src/components/Leva/LevaPanel.tsx
- packages/leva/src/components/Leva/LevaRoot.tsx
- packages/leva/src/components/Leva/StyledFilter.ts
- packages/leva/src/components/Leva/StyledLeva.ts
- packages/leva/src/styles/stitches.config.ts
- packages/leva/stories/panel-options.stories.tsx
This PR aims at giving more flexibility when it comes to using the Leva panel inside a parent node.
```jsx
<Leva
theme={myTheme}  // you can pass a custom theme (see the styling section)
fill             // default = false,  true makes the pane fill the parent dom node it's rendered in
flat             // default = false,  true removes border radius and shadow
oneLineLabels    // default = false, alternative layout for labels, with labels and fields on separate rows  
hideTitleBar     // default = false, hides the GUI header
collapsed        // default = false, when true the GUI is collpased
hidden           // default = false, when true the GUI is hidden
/>
```
> Styles: minor amends on styles

- .changeset/thin-cougars-attack.md
- packages/leva/src/components/Number/RangeSlider.tsx
Hi, this is another small fix
I have fixed this annoying glitch with slider. It happens on some values and probably this is browser calc rounding miss
before
after
> fix slider position overflow

- .github/workflows/main.yml
- .husky/pre-commit
- package.json
This will fail until #273 is merged with all the prettier changes.
Also, use `npm` in pre-commit hook for those of us without yarn (and in the future pnpm) globally installed.
> Run eslint and prettier on all files in CI

- .changeset/tender-parents-mix.md
- packages/leva/src/store.ts
> fix: correct listener path to prevent onEdit callbacks from firing twice

- demo/src/sandboxes/leva-theme/src/App.jsx
It seems like it may have bene used this way before with an additional component. 
Used float because I'm old and lazy.
fixes #318
> docs: output theme json in leva-theme example

- .changeset/tender-walls-camp.md
- demo/src/sandboxes/leva-busy/src/App.tsx
- packages/leva/src/components/UI/Label.tsx
- packages/leva/src/components/UI/StyledUI.ts
As mentioned in #264 tooltips aren't being rendered on hover when the input is disabled.
This is due to pointer events being set to `none` by the `disabled` variant of `StyledInputWrapper`.
- Add a `disabled` variant to `StyledRow` to conditionally remove pointer-events / apply hover styles
- Reset `StyledLabel` pointer-events when `StyledInputWrapper` is `disabled`
- Don't render the "copy" icon when the input is disabled
> fix(leva): disabled labels not showing tooltips

- .changeset/bright-moose-tap.md
- packages/leva/src/useControls.ts
- packages/leva/stories/controlled-inputs.stories.tsx
Should support #222 feature request.
Changes:
- `useControls` returns a getter as a third parameter. 
- `useControls` Typescript setter now checks the type of what are you trying to set. 
Example:
```
const [{ counter }, set, get] = useControls(() => ({ counter: 0} }))
const onClick = useCallback(() => {
set({ counter: get('counter') + 1 })
}, [])
```
[Demo link](https://leva-git-fork-rodrigohamuy-feat-getter-pmndrs.vercel.app/?path=/story/misc-controlled-inputs--external-updates-with-get-and-set)
> feat: `useControls`  returns a `get` function

- packages/leva/package.json
Hey! Firstly, awesome work on Leva. Awesome package.
Fairly likely that this is providing some service that I've not managed to catch from a quick look through the code, but I can't see if there's a reason why `@welldone-software/why-did-you-render` is a production dependency rather than a dev dep? 🙂
Was throwing conflict warnings in a project so I thought I'd check and open this PR in case it was helpful!
> fix: move 'why-did-you-render' to devDependencies

- .changeset/lucky-actors-share.md
- demo/src/sandboxes/leva-busy/src/App.tsx
- demo/src/sandboxes/leva-ui/src/App.jsx
- packages/leva/src/components/Folder/Folder.tsx
- packages/leva/src/components/String/string-plugin.ts
- packages/leva/src/store.ts
- packages/leva/src/types/internal.ts
- packages/leva/src/types/public.ts
- packages/leva/src/utils/input.ts
- packages/leva/stories/Folder.stories.tsx
- packages/leva/stories/input-options.stories.tsx
Allow to set the order in which elements appear, following a rule similar to CSS order property.
Example:
```
useControls(() => ({
last: folder({ firstVal: 0 }, { order: 1, collapsed: true }),
middle: folder({ secondVal: 0 }, { order: -1, collapsed: true }),
first: { value: 0, order: -2 },
}))
```
> feat: Set inputs and folders order

- .changeset/stupid-walls-tap.md
- packages/leva/src/components/Leva/Leva.tsx
- packages/leva/src/utils/react.ts
Resolves #358, semver patch alternative to #330.
Disables React 18 deprecation warnings when creating a legacy root.
> *ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it’s running React 17. Learn more: https://reactjs.org/link/switch-to-createroot*
> fix(Leva): disable dev warning

- .changeset/grumpy-horses-wash.md
- packages/leva/src/components/Folder/StyledFolder.ts
- packages/leva/stories/panel-options.stories.tsx
- packages/plugin-dates/src/Date.stories.tsx
- packages/plugin-dates/src/Date.tsx
To support the date plugin, a CSS change was made that broke scrolling on long panels.
This PR fixes that, by reverting that line of CSS and instead changing the date panel's height depending on wherever the pop-up is open or close. Maybe is not the nicest solution, so open to suggestions!
You can test the fix in the following storybook stories:
- Dates > With Other Fields
- Panel options > Really Long Panel
> fix: scrolling long panels

- docs/advanced/controlled-inputs.md
In the referenced example, `transient` has its value set to `false` (not `true`).
> Fix a typo in `controlled-inputs.md`

- .changeset/grumpy-wombats-pump.md
- packages/leva/package.json
- yarn.lock
Fixes #415 where (effectively) pinned `0.x` dependencies did not specify compatibility with React 18. They've since moved to `1.x` which does and can make better use of semver
> fix(leva): update radiux-ui for peer deps

- docs/configuration.md
👋🏽 
Spent some time trying to figure out why the panel was rendering even when not rendering `<Leva />` based on some preferences, also saw that someone else had the same doubt about how to disable the GUI so I decided to propose some docs.
> docs(configuration): disabling the GUI

- .changeset/clever-experts-perform.md
- packages/leva/package.json
- packages/leva/src/components/Number/Number.tsx
Pointer Lock API allows the user to drag the input label outside the boundaries of the browser, while hiding the cursor. This creates a better experience similar to Blender or any other edition tool.
[More information on Pointer Lock API here](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_Lock_API)
> feat: use Pointer Lock API for Number input

- .changeset/light-tigers-explode.md
- packages/leva/package.json
- packages/leva/src/components/UI/Misc.tsx
- yarn.lock
Upgraded `@radix-ui/*` for React 19 compatibility.
https://www.radix-ui.com/primitives/docs/overview/releases#june-19-2024
```shell
└─┬ leva 0.10.0
├─┬ @radix-ui/react-portal 1.0.2
│ ├── ✕ unmet peer react@"^16.8 || ^17.0 || ^18.0": found 19.0.0
│ ├── ✕ unmet peer react-dom@"^16.8 || ^17.0 || ^18.0": found 19.0.0
│ └─┬ @radix-ui/react-primitive 1.0.2
│   ├── ✕ unmet peer react@"^16.8 || ^17.0 || ^18.0": found 19.0.0
│   ├── ✕ unmet peer react-dom@"^16.8 || ^17.0 || ^18.0": found 19.0.0
│   └─┬ @radix-ui/react-slot 1.0.1
│     ├── ✕ unmet peer react@"^16.8 || ^17.0 || ^18.0": found 19.0.0
│     └─┬ @radix-ui/react-compose-refs 1.0.0
│       └── ✕ unmet peer react@"^16.8 || ^17.0 || ^18.0": found 19.0.0
└─┬ @radix-ui/react-tooltip 1.0.5
├── ✕ unmet peer react@"^16.8 || ^17.0 || ^18.0": …
```
> `@radix-ui/*` upgrades to prevent peerDeps warnings with React 19
