pmndrs/leva

.codesandbox/ci.json, example/src/App.tsx, packages/leva/package.json, packages/leva/src/components/Color/Color.tsx, packages/leva/src/components/Color/StyledColor.ts, packages/leva/src/components/Folder/Folder.tsx, packages/leva/src/components/Folder/StyledFolder.ts, packages/leva/src/components/Leva/Filter.tsx, packages/leva/src/components/Leva/Leva.tsx, packages/leva/src/components/Leva/StyledFilter.ts, packages/leva/src/components/Leva/StyledLeva.ts, packages/leva/src/components/Point2d/Joystick.tsx, packages/leva/src/components/Point2d/StyledJoystick.ts, packages/leva/src/components/UI/Misc.tsx, packages/leva/src/context.ts, packages/leva/src/hooks/useDrag.ts, packages/leva/src/hooks/useToggle.ts, packages/leva/src/styles/stitches.config.ts, yarn.lock
=> Scrolling root

example/src/App.tsx, example/src/index.tsx, packages/leva/src/components/Color/StyledColor.ts, packages/leva/src/components/Control/Control.tsx, packages/leva/src/components/Number/number-plugin.ts, packages/leva/src/components/Point2d/Joystick.tsx, packages/leva/src/components/Vector/vector-plugin.ts, packages/leva/src/components/Vector/vector-utils.ts, packages/leva/src/styles/stitches.config.ts, packages/leva/src/types/public-types.ts, packages/leva/src/utils/hooks/useDragNumber.ts, packages/leva/src/utils/hooks/useInput.ts, packages/leva/src/utils/math.ts
- improves number step calculation
- allows global settings for vectors
- inject react-colourful css in stitches
=> Step improvements color css fix

example/src/index.tsx, packages/leva/src/components/Color/Color.tsx, packages/leva/src/components/UI/Misc.tsx
@marcofugaro you may want to try this see if it fits?
Related: #54
=> Adds autoclose to colorpicker onMouseLeave after a 500ms delay

demo/src/sandboxes/leva-minimal/src/App.jsx, demo/src/sandboxes/leva-scroll/src/App.jsx, packages/leva/package.json, packages/leva/src/components/Interval/Interval.tsx, packages/leva/src/components/Number/Number.tsx, packages/leva/src/components/Number/StyledNumber.ts, packages/leva/src/components/UI/Misc.tsx, packages/leva/src/components/ValueInput/StyledInput.ts, packages/leva/src/components/Vector/Vector.tsx, packages/leva/src/plugins/index.ts, packages/leva/src/styles/stitches.config.ts, yarn.lock
=> styles: remove inner label for range and interval

packages/leva/package.json, packages/leva/src/components/Control/ControlInput.tsx, packages/leva/src/components/UI/Label.tsx, packages/leva/src/components/UI/StyledUI.ts, packages/leva/src/store.ts, packages/leva/src/styles/stitches.config.ts, packages/leva/src/types/internal.ts, packages/leva/src/types/public.ts, packages/leva/stories/input-options.stories.tsx, yarn.lock
https://user-images.githubusercontent.com/5003380/110237005-b31fc800-7f39-11eb-9557-16e5a9fadb33.mov
see: #105
=> Feat: hint on labels

.eslintrc.json, demo/src/sandboxes/leva-minimal/src/App.jsx, demo/src/sandboxes/leva-plugin-spring/src/App.jsx, packages/leva/package.json, packages/leva/src/components/Control/Control.tsx, packages/leva/src/components/Control/ControlInput.tsx, packages/leva/src/components/UI/Label.tsx, packages/leva/src/components/UI/StyledUI.ts, packages/leva/src/hooks/useInput.ts, packages/leva/src/store.ts, packages/leva/src/styles/stitches.config.ts, packages/leva/src/types/internal.ts, packages/leva/src/types/public.ts, packages/leva/src/utils/data.ts, packages/leva/stories/input-options.stories.tsx, yarn.lock
If checkbox is unchecked, the value of the input is `undefined`.
POC:
https://user-images.githubusercontent.com/5003380/110219231-474c4980-7ebe-11eb-8878-b0659f92cb2d.mov
see: #105 
TODO:
=> Feat: add optional checkbox for all inputs

packages/leva/src/components/ButtonGroup/ButtonGroup.tsx, packages/leva/src/components/ButtonGroup/StyledButtonGroup.tsx, packages/leva/src/components/ButtonGroup/StyledButtonGroupButton.ts, packages/leva/src/components/ButtonGroup/index.ts, packages/leva/src/components/Control/Control.tsx, packages/leva/src/helpers/buttonGroup.ts, packages/leva/src/helpers/index.ts, packages/leva/src/types/public.ts, packages/leva/stories/inputs/Button.stories.tsx, packages/leva/stories/inputs/ButtonGroup.stories.tsx
=> feat: button group helper

.changeset/loud-elephants-grin.md, packages/leva/src/components/Folder/Folder.tsx, packages/leva/src/components/Folder/StyledFolder.ts, packages/leva/src/hooks/useToggle.ts, packages/leva/stories/panel-options.stories.tsx
=> Fix: scrollbars should no longer show when folder collapse

.changeset/proud-flowers-visit.md, .github/workflows/main.yml, packages/leva/src/components/Select/Select.tsx, packages/leva/src/components/Select/select-plugin.ts, packages/leva/src/hooks/useValue.ts, packages/leva/src/useControls.ts, packages/leva/src/utils/input.ts, packages/leva/stories/inputs/Select.stories.tsx
=> Fix: have Select accept function as values and options

.changeset/eighty-shoes-protect.md, .changeset/happy-sheep-allow.md, .gitignore, cypress/integration/spec.js, demo/src/sandboxes/leva-busy/src/App.tsx, demo/src/sandboxes/leva-plugin-bezier/src/App.tsx, demo/src/sandboxes/leva-plugin-spring/src/App.tsx, demo/src/sandboxes/leva-ui/src/App.jsx, packages/leva/src/components/Control/Control.tsx, packages/leva/src/components/Control/ControlInput.tsx, packages/leva/src/components/ValueInput/ValueInput.tsx, packages/leva/src/components/Vector/Vector.tsx, packages/leva/src/context.tsx, packages/leva/src/hooks/useInput.ts, packages/leva/src/hooks/useInputSetters.ts, packages/leva/src/plugin.ts, packages/leva/src/store.ts, packages/leva/src/types/internal.ts, packages/leva/src/types/public.ts, packages/leva/src/types/utils.ts, packages/leva/src/utils/input.ts, packages/leva/src/utils/math.ts, packages/plugin-bezier/src/Bezier.stories.tsx
In the typical leva-ui sandbox, when having two boxes, updating a box input before committing and then selecting another box would actually commit the change to the new selected box.
This is an attempt to fix it.
=> Fix: correct update blurred input

.changeset/ninety-eyes-lie.md, packages/leva/src/index.ts, packages/leva/src/store.ts, packages/leva/src/types/internal.ts, packages/leva/src/types/public.test.ts, packages/leva/src/types/public.ts, packages/leva/src/useControls.ts, packages/leva/src/utils/input.ts, packages/leva/stories/input-options.stories.tsx
Early WIP for render mixed with onChange. Namings are all WIP. Maybe it would also make sense to flip the symbol behavior. Invoke onChange and cause re-render by default and skip the re-render only when the onChange handler is wrapped 🤔
=> feat: transient boolean flag

docs/inputs.md
Figured I'll make a separate PR as this is independent from controlled inputs docs.
=> docs: describe Vector2 in inputs.md

.changeset/serious-jeans-hug.md, package.json, packages/leva/src/index.ts, packages/leva/src/types/public.ts, packages/leva/src/utils/input.ts, packages/leva/stories/input-options.stories.tsx
closes https://github.com/pmndrs/leva/issues/200
=> feat: specify explicit input field type

.changeset/olive-news-know.md, packages/leva/src/hooks/useInput.ts, packages/leva/src/store.ts, packages/leva/src/types/internal.ts, packages/leva/src/types/public.ts, packages/leva/src/useControls.ts, packages/leva/src/utils/input.ts, packages/leva/stories/input-options.stories.tsx
=> feat: onChange initial, fromPanel, get context parameter

docs/inputs.md
I figured I'll add it to the docs so I don't have to bother you on Discord again when I forget it :)
=> docs(inputs): describe how `step` affects Vector joystick

.changeset/tricky-lies-tap.md, demo/src/sandboxes/leva-advanced-panels/src/App.jsx, packages/leva/src/hooks/useValuesForPath.ts, packages/leva/src/utils/object.ts
=> fix: double render issue when using nested components

packages/leva/src/styles/stitches.config.ts
bgColor is in this `if` statement always true.
=> redunancy check

docs/advanced/controlled-inputs.md
=> Duplicate code.

.changeset/ninety-apes-do.md, packages/leva/src/components/Boolean/Boolean.tsx, packages/leva/src/components/Image/Image.tsx, packages/leva/src/components/Select/Select.tsx, packages/leva/src/components/ValueInput/ValueInput.tsx, packages/leva/src/types/public.ts, packages/leva/src/utils/input.ts
=> fix: disabled prop should be properly passed to inputs including plugins

.changeset/tidy-flowers-draw.md, demo/package.json, packages/leva/package.json, yarn.lock
close https://github.com/pmndrs/leva/issues/332
=> chore: upgrade @stitches/react to v1.2.8

.changeset/wild-pants-reflect.md, packages/leva/src/components/Number/number-plugin.ts
=> fix: number units can be symbols such as %

.changeset/itchy-kiwis-explain.md, packages/leva/src/components/Interval/interval-plugin.ts, packages/leva/src/store.ts, packages/leva/src/utils/input.ts
=> Fix set interval

.changeset/afraid-cycles-shave.md, packages/leva/src/components/Leva/Filter.tsx, packages/leva/src/components/Leva/LevaRoot.tsx, packages/leva/stories/controlled-inputs.stories.tsx, packages/leva/stories/input-options.stories.tsx, packages/leva/stories/panel-options.stories.tsx
=> feat: add controlled position prop of the leva panel and add onDrag, onDragStart, onDragEnd event handlers

README.md
I just wasted a lot of time setting up new project trying to figure out where the error was coming from, thought I was setting up createRoot wrong, then thought maybe it was a suspense thing, then thought it was an r3f thing, then finally figured out it was leva. Might be a good idea to add to the  readme/getting started that you will get an error in react 18, and how to fix. Great project and I appreciate it though!
=> Add note about error in React 18

.changeset/four-mangos-reply.md, packages/leva/package.json, yarn.lock
Fixes #529
Fixes #512
Fixes #508
Update dependencies in packages/leva/package.json
- Fix to stable releases to ensure compatibility
Avoids breaking joystick and color picker
=> fix(deps): pin joystick and color picker

docs/special-inputs.md
=> docs: add special inputs button example

docs/advanced/controlled-inputs.md, packages/leva/.npmignore
This gives a slight cleanup of the published npm package.
=> chore: add stories to leva's .npmignore

.changeset/two-cherries-walk.md, packages/leva/src/components/Image/Image.tsx, packages/leva/src/context.tsx, packages/leva/src/hooks/useDeepMemo.ts, packages/leva/src/hooks/useInput.ts, packages/leva/src/hooks/useInputSetters.ts, packages/leva/src/hooks/useShallowMemo.ts, packages/plugin-bezier/src/bezier-utils.ts, packages/plugin-dates/package.json, packages/plugin-dates/src/Date.tsx, packages/plugin-dates/src/date-types.ts, yarn.lock
Updates React Calendar to support React 18+ types.
=> fix(plugin-dates): update React Calendar
